# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#info-object
info:
  # REQUIRED. The title of the API.
  title: Example API
  # A short description of the API. CommonMark syntax MAY be used for rich text representation.
  description: This is a example.
  # The contact information for the exposed API.
  contact:
    # The identifying name of the contact person/organization.
    name: "API Support"
  # REQUIRED. The version of the OpenAPI document
  # (which is distinct from the OpenAPI Specification version or the API implementation version).
  version: 0.0.1
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#server-object
servers:
  # REQUIRED. A URL to the target host. This URL supports Server Variables and MAY be relative,
  # to indicate that the host location is relative to the location where the OpenAPI document is being served.
  # Variable substitutions will be made when a variable is named in {brackets}.
  - url: http://localhost
    # An optional string describing the host designated by the URL.
    # CommonMark syntax MAY be used for rich text representation.
    description: Development server
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#components-object
components:
  # https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#security-scheme-object
  securitySchemes:
    api_key:
      # REQUIRED. The type of the security scheme. Valid values are "apiKey", "http", "oauth2", "openIdConnect".
      type: apiKey
      # REQUIRED. The name of the header, query or cookie parameter to be used.
      name: api_key
      # REQUIRED. The location of the API key. Valid values are "query", "header" or "cookie".
      in: header
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#security-requirement-object
security:
  # Each name MUST correspond to a security scheme which is declared in the Security Schemes under the Components Object.
  # If the security scheme is of type "oauth2" or "openIdConnect",
  # then the value is a list of scope names required for the execution,
  # and the list MAY be empty if authorization does not require a specified scope.
  # For other security scheme types, the array MUST be empty.
  - api_key: []
